### PR TITLE
LPS-53479 Web Content expires when "never expire" is set

### PR DESCRIPTION
**Pull request by juliocamarero**
Hi @zsigmondrab, @zsolah 

in order to make it easier for you to write the test, I have created the skeleton and all the methods you may need to finish it.

It shouldn't take long to finish it from here. Once we finish it, it should fail before your changes and pass after them.

Let me know if you need any help,

thanks a lot!

### CODE REVIEW

**Comment by zsolah** [comment]
Hello, thanks. At the moment I'm having an issue running integration tests.

It get this log:

 [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit]
    [junit] Testcase: com.liferay.portlet.journal.service.JournalArticleScheduledTest:BeforeFirstTest:  Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM ex
it.
    [junit]     at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
    [junit]
    [junit]
    [junit] Running com.liferay.portlet.journal.service.JournalArticleScheduledTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] Test com.liferay.portlet.journal.service.JournalArticleScheduledTest FAILED (crashed)

**Comment by juliocamarero** [comment]
Hi @zsolah 

I just tested it and the test run with success for me (after fixing a broken method from yesterday's changes that shouldn't have affected you).

are you doing in portal-impl/ ant test-class -Dtest.class=JournalArticleScheduledTest

**Comment by juliocamarero** [comment]
(you will need the lastest commit I pushed here since there were some changes to the tests infrastructure yesterday)

**Comment by zsolah** [comment]
Hi, I close this and I send you my my final version, thanks for your advice.

**Pull request closed without merging**
